### PR TITLE
Performance improvements & DMagic API fixes

### PR DESCRIPTION
**Pull request by siimav**
Fixed major performance issues with RSS/RO/RP-1 by not calculating the entire science data again after each change on the vessel. Another huge performance improvement came from not checking stored experiments on other unloaded vessels. I made a config toggle for that functionality but it's now disabled by default.
Integration with DMModuleScienceAnimateGeneric also received a couple of fixes.

It would be nice if you'd mark your releases compatible with KSP versions starting from 1.5. CKAN supports that just fine. All you'd need to do is compile this mod with references to KSP 1.5 DLLs and it would work with up to KSP 1.7 and possibly also with future updates. I could do another PR for the version file if you'd like.

### CODE REVIEW

**Comment by Flupster** [comment]
add the version changes your proposing and then I'll merge, build and release sometime this weekend

Thanks for putting in the effort, really appreciated

**Comment by siimav** [comment]
The version file change for supporting multiple versions is now also included. I'll leave incrementing the assembly and release version numbers to you. Also make sure you use KSP 1.5.1 DLLs for compiling the mod now because using the lowest compatible version usually gives the best chances of the code not breaking with updates.

**Comment by Gordon-Dry** [comment]
Is this kind of what was already suggested at that post?
-> https://forum.kerbalspaceprogram.com/index.php?/topic/107661-ksp-145-x-science-ksp-science-report-and-checklist-v517/&do=findComment&comment=3341356

**Comment by siimav** [comment]
No, completely different approach

**Pull request merged**
